---
plugins:
  - react
  - jsx-a11y
  - react-hooks
  - cypress
env:
  node: true
  browser: true
  cypress/globals: true

parser: babel-eslint

extends:
  - "airbnb"

rules:
  no-console: 0
  react/prop-types: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  arrow-parens:
    - 2
    - "as-needed"
  react/jsx-props-no-spreading: 0
  react/static-property-placement: 0
  react/state-in-constructor: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
