export default JSON.stringify([
  '7',
  '7',
  'lobby',
  'phx_reply',
  {
    response: {
      active_games: [
        {
          id: 19887,
          inserted_at: '2020-09-27T13:30:54',
          is_bot: true,
          level: 'medium',
          players: [
            {
              id: -27,
              name: 'HappyQleaner',
              is_bot: true,
              github_id: 35539033,
              lang: 'js',
              editor_text: 'module.exports = () => {\n\n};',
              editor_lang: 'js',
              creator: true,
              game_result: 'undefined',
              check_result: {
                asserts: [],
                asserts_count: 0,
                output: '',
                result: '{"status": "info"}',
                status: 'initial',
                success_count: 0,
              },
              achievements: [
                'played_hundred_games',
                'win_games_with?clojure_cpp_csharp_golang_haskell_js_kotlin_php_python_ruby',
              ],
              rating: 1365,
              rating_diff: 0,
            },
          ],
          state: 'waiting_opponent',
          timeout_seconds: 3600,
          type: 'bot',
        },
        {
          id: 19923,
          inserted_at: '2020-09-28T12:17:11',
          is_bot: true,
          level: 'hard',
          players: [
            {
              id: -18,
              name: 'DenisPython',
              is_bot: true,
              github_id: 35539033,
              lang: 'js',
              editor_text: 'module.exports = () => {\n\n};',
              editor_lang: 'js',
              creator: true,
              game_result: 'undefined',
              check_result: {
                asserts: [],
                asserts_count: 0,
                output: '',
                result: '{"status": "info"}',
                status: 'initial',
                success_count: 0,
              },
              achievements: [
                'played_hundred_games',
                'win_games_with?cpp_csharp_elixir_golang_haskell_java_js_php_python_ruby_ts',
              ],
              rating: 1344,
              rating_diff: 0,
            },
          ],
          state: 'waiting_opponent',
          timeout_seconds: 3600,
          type: 'bot',
        },
        {
          id: 20011,
          inserted_at: '2020-09-30T16:15:49',
          is_bot: true,
          level: 'elementary',
          players: [
            {
              id: -9,
              name: 'UlaBack',
              is_bot: true,
              github_id: 35539033,
              lang: 'ruby',
              editor_text: 'module.exports = () => {\n\n};',
              editor_lang: 'ruby',
              creator: true,
              game_result: 'undefined',
              check_result: {
                asserts: [],
                asserts_count: 0,
                output: '',
                result: '{"status": "info"}',
                status: 'initial',
                success_count: 0,
              },
              achievements: [
                'played_hundred_games',
                'win_games_with?cpp_csharp_elixir_haskell_java_js_php_python_ruby',
              ],
              rating: 1261,
              rating_diff: 0,
            },
          ],
          state: 'waiting_opponent',
          timeout_seconds: 3600,
          type: 'bot',
        },
        {
          id: 20013,
          inserted_at: '2020-09-30T17:14:20',
          is_bot: true,
          level: 'easy',
          players: [
            {
              id: -5,
              name: 'ValyaFront',
              is_bot: true,
              github_id: 35539033,
              lang: 'js',
              editor_text: 'module.exports = () => {\n\n};',
              editor_lang: 'js',
              creator: true,
              game_result: 'undefined',
              check_result: {
                asserts: [],
                asserts_count: 0,
                output: '',
                result: '{"status": "info"}',
                status: 'initial',
                success_count: 0,
              },
              achievements: [
                'played_hundred_games',
                'win_games_with?clojure_cpp_elixir_golang_java_js_php_python_ruby',
              ],
              rating: 1287,
              rating_diff: 0,
            },
          ],
          state: 'waiting_opponent',
          timeout_seconds: 3600,
          type: 'bot',
        },
      ],
    },
    status: 'ok',
  },
]);
